
apiVersion: v1
kind: Service
metadata:
  name: oms-v6-service
  labels:
    app: oms-v6
spec:
  type: LoadBalancer
  selector:
    app: oms-v6
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
